---
# Additional yt-dlp options
ytdlOptions:
#  - -f
#  - "bestvideo*+bestaudio/best"
#  - -o
#  - "./download/%(id)s.%(ext)s"

# Additional streamlink options
streamlinkOptions:
  # - --http-cookie
  # - tc_id=xxx
  # - --http-cookie
  # - tc_ss=xxx

twitcasting:
  # Refresh interval in millisecond
  interval: 10000
  users:
    - nakiriayame

webhooks:
  discord:
    - active: true
      urls:
        # - https://discord.com/api/webhooks/<token>
      twitcasting:
        - <all>
      message: "<@153363129915539457>"
