---
# Output directory (default to current working folder)
# output: d:/downloads

# Additional streamlink options
streamlinkOptions:
  # - --http-cookie
  # - tc_id=xxx
  # - --http-cookie
  # - tc_ss=xxx

twitcasting:
  # Refresh interval in millisecond
  interval: 30000
  users:
    - nakiriayame

webhooks:
  discord:
    - active: true
      urls:
        - https://discord.com/api/webhooks/xxx
      twitcasting:
        - <all>
      message: "<@153363129915539457>"
