---
# Output directory (default to current working folder)
# output: d:/downloads

# Additional yt-dlp options
ytdlOptions:
#  - --config-location
#  - d:/yt-dlp/yt-dlp.conf

twitcasting:
  # Refresh interval in millisecond
  interval: 30000
  users:
  - nakiriayame

youtube:
  # Refresh interval in millisecond
  interval: 30000
  users:
  - UC7fk0CB07ly8oSl0aqKkqFg # Nakiri Ayame Ch. 百鬼あやめ

webhooks:
  discord:
  - active: true
    urls:
    - https://discord.com/api/webhooks/xxx
    twitcasting:
    - <all>
    youtube:
    - <all>
    mentions:
      roleIds:
      - 'xxx'
      userIds:
      - 'xxx'
