---
version: "3.8"
services:
  stream-crawler:
    image: ghcr.io/hitomarukonpaku/stream-crawler:latest
    container_name: stream-crawler
    user: "1000:1000"
    restart: always
    network_mode: "host"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./logs:/app/logs
      - ./download:/app/download
